const nowIso = () => new Date().toISOString();

export const createInitialState = () => ({
  workspace: {
    id: 'fideo-demo',
    slug: 'fideo-operacion',
    version: 1,
    mode: 'vue3-static-sfc',
  },
  employees: [
    { id: 'emp-admin', name: 'Admin Fideo', role: 'Admin', status: 'active' },
    { id: 'emp-pack', name: 'Empaque Norte', role: 'Empacador', status: 'active' },
    { id: 'emp-route', name: 'Ruta Centro', role: 'Repartidor', status: 'idle' },
  ],
  customers: [
    {
      id: 'cus-lupita',
      name: 'Fruteria Lupita',
      creditStatus: 'Confiable',
      creditLimit: 25000,
      contacts: [{ name: 'Lupita', isPrimary: true }],
      specialPrices: [],
      deliveryNotes: 'Entregar antes de las 11:00.',
    },
    {
      id: 'cus-mercado',
      name: 'Mercado Central',
      creditStatus: 'Vigilar',
      creditLimit: 18000,
      contacts: [{ name: 'Encargado Anden', isPrimary: true }],
      specialPrices: [],
      deliveryNotes: 'Confirmar anden antes de descargar.',
    },
  ],
  suppliers: [
    {
      id: 'sup-huerta',
      name: 'Huerta del Sur',
      contact: 'WhatsApp proveedor',
      supplies: [
        {
          varietyId: 'var-mango-ataulfo',
          baseCost: 260,
          freightCost: 34,
          availableSizes: ['Mediano', 'Grande'],
          packagingOptions: [{ name: 'Caja', cost: 18 }],
          notes: 'Fruta firme para maduracion controlada.',
        },
      ],
    },
    {
      id: 'sup-chiapas',
      name: 'Cooperativa Chiapas',
      contact: 'Compras regionales',
      supplies: [
        {
          varietyId: 'var-platano-chiapas',
          baseCost: 185,
          freightCost: 22,
          availableSizes: ['Mediano'],
          packagingOptions: [{ name: 'Caja', cost: 14 }],
          notes: 'Alta rotacion semanal.',
        },
      ],
    },
  ],
  productGroups: [
    {
      id: 'pg-mango',
      name: 'Mango',
      category: 'Tropical',
      unit: 'cajas',
      icon: 'MG',
      archived: false,
      varieties: [
        {
          id: 'var-mango-ataulfo',
          name: 'Ataulfo',
          aliases: ['ataulfo', 'mango ataulfo'],
          sizes: ['Mediano', 'Grande'],
          archived: false,
        },
      ],
    },
    {
      id: 'pg-platano',
      name: 'Platano',
      category: 'Tropical',
      unit: 'cajas',
      icon: 'PL',
      archived: false,
      varieties: [
        {
          id: 'var-platano-chiapas',
          name: 'Chiapas',
          aliases: ['chiapas'],
          sizes: ['Mediano'],
          archived: false,
        },
      ],
    },
    {
      id: 'pg-papaya',
      name: 'Papaya',
      category: 'Tropical',
      unit: 'cajas',
      icon: 'PP',
      archived: false,
      varieties: [
        {
          id: 'var-papaya-maradol',
          name: 'Maradol',
          aliases: ['maradol'],
          sizes: ['Grande'],
          archived: false,
        },
      ],
    },
  ],
  sizes: {
    Mediano: { icon: 'M', archived: false },
    Grande: { icon: 'G', archived: false },
  },
  categoryIcons: {
    Tropical: 'TR',
    Activos: 'AC',
  },
  stateIcons: {
    Verde: 'VE',
    Entrado: 'EN',
    Maduro: 'MA',
    Suave: 'SU',
  },
  warehouses: [
    { id: 'wh-main', name: 'Bodega Principal', icon: 'WH', archived: false },
    { id: 'wh-floor', name: 'Piso Sucursal', icon: 'PV', archived: false },
  ],
  prices: [
    { varietyId: 'var-mango-ataulfo', size: 'Mediano', quality: 'Normal', state: 'Maduro', price: 470 },
    { varietyId: 'var-platano-chiapas', size: 'Mediano', quality: 'Normal', state: 'Entrado', price: 310 },
    { varietyId: 'var-papaya-maradol', size: 'Grande', quality: 'Con Defectos', state: 'Suave', price: 180 },
  ],
  crateTypes: [
    {
      id: 'crate-green',
      name: 'Caja verde',
      shortCode: 'CV',
      color: 'verde',
      size: 'Mediano',
      cost: 38,
      dimensions: { width: 40, depth: 30, height: 20 },
    },
    {
      id: 'crate-wood',
      name: 'Caja madera',
      shortCode: 'CM',
      color: 'madera',
      size: 'Grande',
      cost: 52,
      dimensions: { width: 45, depth: 35, height: 22 },
    },
  ],
  crateInventory: [
    { crateTypeId: 'crate-green', quantityOwned: 120 },
    { crateTypeId: 'crate-wood', quantityOwned: 80 },
  ],
  expenses: [],
  fixedAssets: [
    {
      id: 'fa-truck-1',
      name: 'Camioneta reparto',
      category: 'Vehiculos',
      status: 'Activo',
      cost: 185000,
      purchaseDate: nowIso(),
      photoUrl: '',
      metadata: { placas: 'FIDEO-01', capacidad: '1.5t' },
    },
    {
      id: 'fa-scale-1',
      name: 'Bascula piso',
      category: 'Basculas',
      status: 'Activo',
      cost: 14500,
      purchaseDate: nowIso(),
      photoUrl: '',
      metadata: { precision: '50g' },
    },
  ],
  ripeningRules: [
    { id: 'rr-mango-1', varietyId: 'var-mango-ataulfo', fromState: 'Entrado', toState: 'Maduro', days: 2 },
  ],
  inventory: [
    {
      id: 'inv-1',
      varietyId: 'var-mango-ataulfo',
      product: 'Mango Ataulfo',
      size: 'Mediano',
      quality: 'Normal',
      state: 'Maduro',
      quantity: 82,
      warehouseId: 'wh-main',
      location: 'Piso de Venta',
      packagingId: 'crate-green',
      entryDate: nowIso(),
    },
    {
      id: 'inv-2',
      varietyId: 'var-platano-chiapas',
      product: 'Platano Chiapas',
      size: 'Mediano',
      quality: 'Normal',
      state: 'Entrado',
      quantity: 44,
      warehouseId: 'wh-main',
      location: 'Maduracion',
      packagingId: 'crate-green',
      entryDate: nowIso(),
    },
    {
      id: 'inv-3',
      varietyId: 'var-papaya-maradol',
      product: 'Papaya Maradol',
      size: 'Grande',
      quality: 'Con Defectos',
      state: 'Suave',
      quantity: 18,
      warehouseId: 'wh-floor',
      location: 'Piso de Venta',
      packagingId: 'crate-wood',
      entryDate: nowIso(),
    },
  ],
  sales: [
    {
      id: 'sale-1',
      customerId: 'cus-lupita',
      customer: 'Fruteria Lupita',
      product: 'Mango Ataulfo',
      productGroupName: 'Mango',
      varietyName: 'Ataulfo',
      varietyId: 'var-mango-ataulfo',
      size: 'Mediano',
      quality: 'Normal',
      state: 'Maduro',
      quantity: 24,
      cogs: 7488,
      unit: 'cajas',
      price: 11280,
      total: 11280,
      destination: 'Sucursal Centro',
      status: 'Pendiente de Empaque',
      paymentStatus: 'Pendiente',
      paymentMethod: 'Credito',
      assignedEmployeeId: null,
      timestamp: nowIso(),
      deliveryDeadline: nowIso(),
    },
    {
      id: 'sale-2',
      customerId: 'cus-mercado',
      customer: 'Mercado Central',
      product: 'Platano Chiapas',
      productGroupName: 'Platano',
      varietyName: 'Chiapas',
      varietyId: 'var-platano-chiapas',
      size: 'Mediano',
      quality: 'Normal',
      state: 'Entrado',
      quantity: 30,
      cogs: 6630,
      unit: 'cajas',
      price: 9300,
      total: 9300,
      destination: 'Anden 4',
      status: 'En Ruta',
      paymentStatus: 'Parcial',
      paymentMethod: 'Credito',
      assignedEmployeeId: 'emp-route',
      timestamp: nowIso(),
      deliveryDeadline: nowIso(),
    },
  ],
  payments: [],
  purchaseOrders: [
    {
      id: 'po-demo-mango',
      supplierId: 'sup-huerta',
      varietyId: 'var-mango-ataulfo',
      size: 'Mediano',
      packaging: 'Caja',
      quantity: 40,
      totalCost: 12480,
      status: 'Ordenado',
      orderDate: nowIso(),
      expectedArrivalDate: nowIso(),
      paymentMethod: 'Credito',
    },
  ],
  cashDrawers: [
    { id: 'drawer-main', name: 'Caja Principal', status: 'Abierta', balance: 5000, lastOpened: nowIso() },
  ],
  cashDrawerActivities: [],
  crateLoans: [
    {
      id: 'loan-mercado-green',
      customerId: 'cus-mercado',
      customer: 'Mercado Central',
      crateTypeId: 'crate-green',
      quantity: 12,
      timestamp: nowIso(),
      dueDate: nowIso(),
      status: 'Prestado',
    },
  ],
  taskAssignments: [
    {
      id: 'task-pack-sale-1',
      taskId: 'pack-sale-1',
      kind: 'PACK_ORDER',
      saleId: 'sale-1',
      title: 'Empacar venta Fruteria Lupita',
      description: '24 x Mango Ataulfo Mediano',
      role: 'Empacador',
      employeeId: 'emp-pack',
      employeeName: 'Empaque Norte',
      customerId: 'cus-lupita',
      customerName: 'Fruteria Lupita',
      priority: 'high',
      status: 'assigned',
      createdAt: nowIso(),
      updatedAt: nowIso(),
    },
    {
      id: 'task-route-sale-2',
      taskId: 'route-sale-2',
      kind: 'DELIVER_ORDER',
      saleId: 'sale-2',
      title: 'Confirmar entrega Mercado Central',
      description: 'Anden 4',
      role: 'Repartidor',
      employeeId: 'emp-route',
      employeeName: 'Ruta Centro',
      customerId: 'cus-mercado',
      customerName: 'Mercado Central',
      priority: 'high',
      status: 'blocked',
      blockReason: 'Cliente pidio cambio de horario',
      blockedReason: 'Cliente pidio cambio de horario',
      createdAt: nowIso(),
      updatedAt: nowIso(),
    },
  ],
  taskReports: [
    {
      id: 'report-route-sale-2',
      taskId: 'route-sale-2',
      kind: 'blocker',
      status: 'open',
      severity: 'high',
      summary: 'Cambio de horario sin confirmar',
      createdAt: nowIso(),
      employeeId: 'emp-route',
      employeeName: 'Ruta Centro',
    },
  ],
  messages: [
    {
      id: 'msg-demo-offer',
      sender: 'Fruteria Lupita',
      text: 'promo de mango maduro para clientes frecuentes',
      timestamp: nowIso(),
      status: 'pending',
    },
  ],
  messageTemplates: [
    {
      id: 'tpl-ticket',
      type: 'ticket',
      name: 'Ticket WhatsApp',
      content: 'Gracias {{customer}}, tu pedido {{order_id}} va en camino.',
      variables: ['customer', 'order_id'],
    },
    {
      id: 'tpl-promo',
      type: 'promotion',
      name: 'Promocion directa',
      content: '{{customer}}, hoy tenemos {{product}} a precio especial.',
      variables: ['customer', 'product'],
    },
    {
      id: 'tpl-reminder',
      type: 'payment_reminder',
      name: 'Recordatorio de pago',
      content: '{{customer}}, tu saldo pendiente es {{balance}}.',
      variables: ['customer', 'balance'],
    },
  ],
  push: {
    enabled: false,
    bindingStatus: 'dry-run',
    permission: false,
    tags: {},
    aliases: {},
    lastError: '',
  },
  systemPrompt: 'Interpreta mensajes de Fideo con prioridad en ventas, compras, precios, entregas y ofertas.',
  activityLog: [],
  integrations: {
    pocketbase: { status: 'pending', label: 'PocketBase snapshot runtime' },
    veeper: { status: 'pending', label: 'Veeper WhatsApp handoff' },
    ai: { status: 'dry-run', label: 'codex-goal AI engines' },
  },
});

export const deriveMetrics = (state) => {
  const openReports = state.taskReports.filter((report) => report.status !== 'resolved');
  const totalSales = state.sales.reduce((sum, sale) => sum + Number(sale.total || 0), 0);
  const inventoryUnits = state.inventory.reduce((sum, item) => sum + Number(item.quantity || 0), 0);

  return {
    openExceptions: openReports.length,
    totalSales,
    inventoryUnits,
    activeStaff: state.employees.filter((employee) => employee.status === 'active').length,
  };
};

export const buildExceptionQueue = (state) =>
  state.taskReports
    .filter((report) => report.status !== 'resolved')
    .map((report) => {
      const task = state.taskAssignments.find((item) => item.taskId === report.taskId);
      return {
        id: `task_report:${report.id}`,
        kind: 'task_blocked',
        severity: report.severity || 'normal',
        title: report.summary || task?.title || 'Excepcion operativa',
        detail: task?.blockedReason || task?.blockReason || report.detail || 'Requiere seguimiento.',
        taskId: report.taskId,
        reportId: report.id,
        employeeId: report.employeeId || task?.employeeId || null,
        employeeName: report.employeeName || task?.employeeName || null,
        createdAt: report.createdAt,
      };
    });
